### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by jrayzero** [mitll/MatchIT#6]
*general*
- [ ] allocate (n^2-n)/2 elements instead of n^2 for comparison
- [x] change testing code so that it sorts lines and compares (since tiling can change the order)
- [ ] bucketing

*optimizations*
- [ ] allow variable sized direct fields. Sometimes, we know the size at runtime (for example, the traceback length in NW is known once the matrices are computed, so we should be able to pass that information along). Do this with something like a -2 for the dimensions.
- [ ] parallelization
